export enum CLICommand {
  AddDependencies = 'adddependencies',
  Deploy = 'deploy',
  ImportBundle = 'importbundle',
  ImportFiles = 'importfiles',
  ImportObjects = 'importobjects',
  ListBundles = 'listbundles',
  ListFiles = 'listfiles',
  ListMissingDependencies = 'listmissingdependencies',
  ListObjects = 'listobjects',
  Preview = 'preview',
  Update = 'update',
  UpdateCustomRecordsWithInstances = 'updatecustomrecordwithinstances',
  Validate = 'validate',
}
