export enum CLICommand {
  AddDependencies = 'adddependencies',
  CreateProject = 'createproject',
  Deploy = 'deploy',
  ImportBundle = 'importbundle',
  ImportFiles = 'importfiles',
  ImportObjects = 'importobjects',
  IssueToken = 'issuetoken',
  ListBundles = 'listbundles',
  ListConfiguration = 'listconfiguration',
  ListFiles = 'listfiles',
  ListMissingDependencies = 'listmissingdependencies',
  ListObjects = 'listobjects',
  Preview = 'preview',
  RevokeToken = 'revoketoken',
  SaveToken = 'authenticate',
  Update = 'update',
  UpdateCustomRecordsWithInstances = 'updatecustomrecordwithinstances',
  // UploadFolders = 'uploadfolders',
  Validate = 'validate'
}
